export const LOAD_ARTICLES = 'LOAD_ARTICLES';

export const LOAD_MOST_VISITED = 'LOAD_MOST_VISITED_ARTICLES';

export const LOAD_MOST_RECENT = 'LOAD_MOST_RECENT_ARTICLES';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const SET_SELECTED = 'SET_SELECTED';

export const SET_IS_FETCHED = 'SET_IS_FETCHED';
